### ISSUE TITLE
Add a login with persistence in firebase

### ISSUE THREAD

**Issue by nholdsworth** [nholdsworth/Class-Project-1#18]
- [x]  Add an input form for user login name to html
- [x]  Set a variable to store the username in javascript
- [ ]  make sure that no two users get the same name
- [ ]  Push the data into firebase: database.ref().push({
       userName: userName,
       dinnerTable: dinnerTable
}).
- [ ] write the so that when the user types in their username their dinerTable shows their recipes

**Comment by packleader206** [comment]
assigned and completed code for firebase persistence for user authentication via email/password method.  Group consensus to not utilize user login subsequently.  Closing issue as a result.
